### PR TITLE
update dropsondes metadata

### PR DESCRIPTION
**Pull request by Geet-George**
Changes:
1. add `pressure` to variables
2. add `EUREC4A_JOANNE` to projects (`part of`)
3. include Felix and Sandrine also in `pi`

### CODE REVIEW

**Comment by Geet-George** [comment]
Ahh.. Seems like the tests have passed! Don't know what changed since yesterday....

**Comment by d70-t** [comment]
I triggered a re-run of the test. The reason why it was failing was because the crossref API did not answer and therefore no additional metadata for DOIs from within this repository could be fetched. I've put caching for the DOI information in place, such that this kind of error should appear less likely.
However, there's still a little bug in your changes, which I hope would be caught by the improved testing scripts. Could you merge the current master back into your branch to see if it works?

**Comment by Geet-George** [comment]
Okay, so now the test says that it doesn't recognise the contact `sandrine`. I am hoping that that was the error you were expecting... :P

**Comment by d70-t** [comment]
Jippee, it works :-) Would you also fix it? Afterwards I'd merge it.

**Comment by Geet-George** [comment]
Juhuu! Seems like it works now. Only that `part of` does not take lists... But I guess that is okay for now.

**Pull request merged**
